name: ci
run-name: ci
on:
  push:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      TAG: 0.0.${{ github.run_number }}
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Ugly Debug
          run: |
            echo ${{ github.repository }}
            echo ${{ github.actor }}
            echo ${{ secrets.GITHUB_TOKEN }}
            echo ${{ env.TAG }}
            echo "node --version: $(node --version)"
            echo "npx --version: $(npx --version)"
            echo "npm --version: $(npm --version)"
            echo "yarn --version: $(yarn --version)"
        - uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Ugly Debug2
          run: |
              echo "node --version: $(node --version)"
              echo "npx --version: $(npx --version)"
              echo "npm --version: $(npm --version)"
              echo "yarn --version: $(yarn --version)"
              npm install -g corepack
        - name: Backstage Init
          run: |
            npm install -g @backstage/create-app@latest
            export BACKSTAGE_APP_NAME=sylwetan-backstage
            npx @backstage/create-app@latest --path src --skip-install
        - name: Plugins
          run: |
            yarn --cwd src/packages/backend add @backstage/plugin-scaffolder-backend-module-github
            yarn --cwd src/packages/backend add @backstage/plugin-catalog-backend-module-github
            cp packages/backend/src/index.ts src/packages/backend/src/index.ts
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to ghcr
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push container image
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ghcr.io/${{ github.repository }}:${{ env.TAG }},ghcr.io/${{ github.repository }}:latest
            build-args: |
              SRC=src
            cache-from: type=gha
            cache-to: type=gha,mode=max
            platforms: linux/amd64,linux/arm64
