name: ci
run-name: ci
on:
  push:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      TAG: 0.0.${{ github.run_number }}
      SRC: backstage
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Ugly Debug
          run: |
            echo ${{ github.repository }}
            echo ${{ github.actor }}
            echo ${{ secrets.GITHUB_TOKEN }}
            echo ${{ env.TAG }}
            echo "node --version: $(node --version)"
            echo "npx --version: $(npx --version)"
            echo "npm --version: $(npm --version)"
            echo "yarn --version: $(yarn --version)"
            echo "ls -ltrh: $(ls -ltrh)"
        # - uses: actions/setup-node@v4
        #   with:
        #     node-version: 20
        - name: Setup Tools
          run: |
              npm install -g corepack
        - name: Backstage Init
          run: |
            npm install -g @backstage/create-app@latest
            export BACKSTAGE_APP_NAME=backstage
            npx @backstage/create-app@latest --path backstage --skip-install
            echo "ls -ltrh: $(ls -ltrh)"
            echo "ls -ltrh ${{ env.src }}: $(ls -ltrh ${{ env.src }})"
            echo "ls -ltrh ${{ env.src }}/examples: $(ls -ltrh ${{ env.src }}/examples)"
        - name: Plugins
          run: |
            yarn --cwd ${{ env.src }}/packages/backend add @backstage/plugin-scaffolder-backend-module-github
            yarn --cwd ${{ env.src }}/packages/backend add @backstage/plugin-catalog-backend-module-github
            cp packages/backend/src/index.ts ${{ env.src }}/packages/backend/src/index.ts
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to ghcr
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push container image
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ghcr.io/${{ github.repository }}:${{ env.TAG }},ghcr.io/${{ github.repository }}:latest
            build-args: |
              SRCOLD=src
              SRC=backend
            cache-from: type=gha
            cache-to: type=gha,mode=max
            platforms: linux/amd64,linux/arm64
