name: ci
run-name: ci
on:
  push:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      TAG: 0.0.${{ github.run_number }}
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Plugins
          run: |
            yarn --cwd src/packages/backend add @backstage/plugin-scaffolder-backend-module-github
            yarn --cwd src/packages/backend add @backstage/plugin-catalog-backend-module-github
            cp packages/backend/src/index.ts src/packages/backend/src/index.ts
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to ghcr
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push container image
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ghcr.io/${{ github.repository }}:${{ env.TAG }},ghcr.io/${{ github.repository }}:latest
            build-args: |
              SRC=src
            cache-from: type=gha
            cache-to: type=gha,mode=max
            platforms: linux/amd64,linux/arm64
